name: Auto Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Reading the changelog configuration and generating the changelog based on commit messages
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ".github/changelog-config.json"
          mode: "COMMIT" # Generate changelog based on commit messages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Creating a GitHub release with the generated changelog as the release notes
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
          prerelease: false