name: Deploy Fuenzer Bot

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment script on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/fuenzer-bot
            
            # Get the latest code from the main branch
            git fetch origin
            
            # Reset local changes and update to the latest code
            git reset --hard origin/main
            
            # Install dependencies
            npm install
            
            # Restart bot
            pm2 restart fuenzerbot || pm2 start src/index.js --name fuenzerbot